default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: sinatra_admin
  timeout: 5000
  reaping_frequency: 30
  pool: 5

development:
  <<: *default
  database: app_sinatra_dev
  password: password

test:
  <<: *default
  database: app_sinatra_test
  password: password

production:
  <<: *default
  database: app_sinatra_prod
  password: password